version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: energy
    ports: ["5432:5432"]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
  api:
    build: .
    depends_on: [db]
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/energy?sslmode=disable
      JWT_SECRET: devsecret-change-me
      ADDR: :8080
    ports: ["8080:8080"]
volumes:
  pgdata:
